/**
 * IE551MapToInternalStatusInformation.java
 *
 * This file was generated by MapForce 2014r2sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */
package com.mapforce;
import com.altova.mapforce.*;
import com.altova.types.*;
import com.altova.xml.*;
import java.util.*;

public class IE551MapToInternalStatusInformation extends com.altova.TraceProvider 
{
	private boolean runDoesCloseAll = true;
	public void setCloseObjectsAfterRun(boolean c) {runDoesCloseAll = c;}
	public boolean getCloseObjectsAfterRun() {return runDoesCloseAll;}

	
	static class main implements IEnumerable
	{
		com.altova.mapforce.IMFNode var1_instance_IE551;
	
		public main(com.altova.mapforce.IMFNode var1_instance_IE551)
		{
			this.var1_instance_IE551 = var1_instance_IE551;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}
		
		public static class Enumerator implements IEnumerator
		{
			int pos = 0;
			int state = 2;
			Object current;
			main closure;
			com.altova.mapforce.IEnumerable var2_filter_elements_qname;
			public Enumerator(main closure) 
			{
				this.closure = closure;
			}
			
			public Object current() {return current;}
			
			public int position() {return pos;}
			
			public boolean moveNext() throws Exception
			{
				while (state != 0)
				{
					switch (state) 
					{
					case 2:	if (moveNext_2()) return true; break;
 					}
				}
				return false;
			}

			private boolean moveNext_2() throws Exception {
				state = 0;				
				var2_filter_elements_qname = new com.altova.functions.Core.SequenceCache(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ExportNoRelease", "http://www.ros.ie/schemas/ecs/IE551/v1"), closure.var1_instance_IE551));
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("InternalStatusInformation", ""), (new seq1_join(var2_filter_elements_qname)));
				pos++;
				return true;
			}

			
			public void close()
			{
				try
				{
				}
				catch (Exception e)
				{
				}
			}
		}
				
	}
	static class seq1_join implements IEnumerable
	{
		com.altova.mapforce.IEnumerable var1_filter_elements_qname;
	
		public seq1_join(com.altova.mapforce.IEnumerable var1_filter_elements_qname)
		{
			this.var1_filter_elements_qname = var1_filter_elements_qname;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}
		
		public static class Enumerator implements IEnumerator
		{
			int pos = 0;
			int state = 1;
			Object current;
			seq1_join closure;
			public Enumerator(seq1_join closure) 
			{
				this.closure = closure;
			}
			
			public Object current() {return current;}
			
			public int position() {return pos;}
			
			public boolean moveNext() throws Exception
			{
				while (state != 0)
				{
					switch (state) 
					{
					case 1:	if (moveNext_1()) return true; break;
					case 2:	if (moveNext_2()) return true; break;
 					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				current = com.altova.functions.Core.createAttribute(com.altova.functions.Core.createQName("xsi:noNamespaceSchemaLocation", "http://www.w3.org/2001/XMLSchema-instance"), com.altova.functions.Core.box("C:/Users/moredata/Desktop/export/IE551MapToInternalStatusInformation/InternalStatusInformation.xsd"));
				pos++;
				return true;
			}
			private boolean moveNext_2() throws Exception {
				state = 0;				
				if (!(com.altova.functions.Core.exists(closure.var1_filter_elements_qname))) {state = 0; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("GoodsDeclaration", ""), (new seq2_join(closure.var1_filter_elements_qname)));
				pos++;
				return true;
			}

			
			public void close()
			{
				try
				{
				}
				catch (Exception e)
				{
				}
			}
		}
				
	}
	static class seq2_join implements IEnumerable
	{
		com.altova.mapforce.IEnumerable var1_filter_elements_qname;
	
		public seq2_join(com.altova.mapforce.IEnumerable var1_filter_elements_qname)
		{
			this.var1_filter_elements_qname = var1_filter_elements_qname;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}
		
		public static class Enumerator implements IEnumerator
		{
			int pos = 0;
			int state = 1;
			Object current;
			seq2_join closure;
			public Enumerator(seq2_join closure) 
			{
				this.closure = closure;
			}
			
			public Object current() {return current;}
			
			public int position() {return pos;}
			
			public boolean moveNext() throws Exception
			{
				while (state != 0)
				{
					switch (state) 
					{
					case 1:	if (moveNext_1()) return true; break;
					case 6:	if (moveNext_6()) return true; break;
					case 11:	if (moveNext_11()) return true; break;
					case 16:	if (moveNext_16()) return true; break;
					case 21:	if (moveNext_21()) return true; break;
 					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 6;				
				if (!(com.altova.functions.Core.exists(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Ucr", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("GoodsShipment", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Declaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ExportCustomsDeclaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname))))))))))) {state = 6; return false; }
				if (!(com.altova.functions.Core.exists(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("TraderReferenceIdentifier", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Ucr", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("GoodsShipment", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Declaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ExportCustomsDeclaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname))))))))))))) {state = 6; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("ReferenceNumber", ""), com.altova.functions.Core.box(com.altova.CoreTypes.nodeToString((com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("TraderReferenceIdentifier", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Ucr", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("GoodsShipment", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Declaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ExportCustomsDeclaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname))))))))))))));
				pos++;
				return true;
			}
			private boolean moveNext_6() throws Exception {
				state = 11;				
				if (!(com.altova.functions.Core.exists(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Ucr", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("GoodsShipment", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Declaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ExportCustomsDeclaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname))))))))))) {state = 11; return false; }
				if (!(com.altova.functions.Core.exists(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("IdentificationIdentifier", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Ucr", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("GoodsShipment", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Declaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ExportCustomsDeclaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname))))))))))))) {state = 11; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("UCRNumber", ""), com.altova.functions.Core.box(com.altova.CoreTypes.nodeToString((com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("IdentificationIdentifier", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Ucr", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("GoodsShipment", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Declaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ExportCustomsDeclaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname))))))))))))));
				pos++;
				return true;
			}
			private boolean moveNext_11() throws Exception {
				state = 16;				
				if (!(com.altova.functions.Core.exists(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Consignment", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("GoodsShipment", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Declaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ExportCustomsDeclaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname))))))))))) {state = 16; return false; }
				if (!(com.altova.functions.Core.exists(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("IESummaryDeclarationIdentifier", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Consignment", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("GoodsShipment", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Declaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ExportCustomsDeclaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname))))))))))))) {state = 16; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("OrderNumber", ""), com.altova.functions.Core.box(com.altova.CoreTypes.nodeToString((com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("IESummaryDeclarationIdentifier", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Consignment", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("GoodsShipment", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Declaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ExportCustomsDeclaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname))))))))))))));
				pos++;
				return true;
			}
			private boolean moveNext_16() throws Exception {
				state = 21;				
				if (!(com.altova.functions.Core.exists(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ControlResult", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Declaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ExportCustomsDeclaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname))))))))) {state = 21; return false; }
				if (!(com.altova.functions.Core.exists(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("DateLimit", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ControlResult", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Declaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ExportCustomsDeclaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname))))))))))) {state = 21; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("DateNewStatus", ""), com.altova.functions.Core.box(com.altova.CoreTypes.nodeToString((com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("DateLimit", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ControlResult", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Declaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ExportCustomsDeclaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname))))))))))));
				pos++;
				return true;
			}
			private boolean moveNext_21() throws Exception {
				state = 0;				
				if (!(com.altova.functions.Core.exists(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Agent", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Declaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ExportCustomsDeclaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname))))))))) {state = 0; return false; }
				if (!(com.altova.functions.Core.exists(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("StatusCode", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Agent", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Declaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ExportCustomsDeclaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname))))))))))) {state = 0; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("NewStatus", ""), com.altova.functions.Core.box(com.altova.CoreTypes.integerToString(com.altova.CoreTypes.longToInteger(com.altova.CoreTypes.intToLong(com.altova.CoreTypes.longToInt(com.altova.CoreTypes.integerToLong(com.altova.CoreTypes.decimalToInteger(com.altova.CoreTypes.parseDecimal(com.altova.CoreTypes.nodeToString((com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("StatusCode", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Agent", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Declaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ExportCustomsDeclaration", "http://www.ros.ie/schemas/ecs/IE551/v1"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname)))))))))))))))))));
				pos++;
				return true;
			}

			
			public void close()
			{
				try
				{
				}
				catch (Exception e)
				{
				}
			}
		}
				
	}
	static class Outer implements IEnumerable
	{
		com.altova.mapforce.IMFNode var1_instance_IE551;
	
		public Outer(com.altova.mapforce.IMFNode var1_instance_IE551)
		{
			this.var1_instance_IE551 = var1_instance_IE551;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}
		
		public static class Enumerator implements IEnumerator
		{
			int pos = 0;
			int state = 1;
			Object current;
			Outer closure;
			IEnumerator var2_box;
			public Enumerator(Outer closure) 
			{
				this.closure = closure;
			}
			
			public Object current() {return current;}
			
			public int position() {return pos;}
			
			public boolean moveNext() throws Exception
			{
				while (state != 0)
				{
					switch (state) 
					{
					case 1:	if (moveNext_1()) return true; break;
					case 2:	if (moveNext_2()) return true; break;
					case 3:	if (moveNext_3()) return true; break;
 					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var2_box = ((new main(closure.var1_instance_IE551))).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 2;				
				if (!var2_box.moveNext()) {state = 3; return false; }
				current = var2_box.current();
				pos++;
				return true;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				var2_box.close(); var2_box = null;
				return false;
			}

			
			public void close()
			{
				try
				{
				var2_box.close(); var2_box = null;
				}
				catch (Exception e)
				{
				}
			}
		}
				
	}



	// instances
	protected org.w3c.dom.Node varIE5513Instance;

	public void run(String IE5513SourceFilename, String InternalStatusInformation2TargetFilename) throws Exception {
		// open source streams
		writeTrace("Loading " + IE5513SourceFilename + "...\n");
		com.altova.io.FileInput IE5513Source = new com.altova.io.FileInput(IE5513SourceFilename);
		// open target stream
		com.altova.io.FileOutput InternalStatusInformation2Target = new com.altova.io.FileOutput(InternalStatusInformation2TargetFilename);

		// run
		run(IE5513Source, InternalStatusInformation2Target);

		// close source streams
		IE5513Source.close();
		// close target stream
		writeTrace("Saving " + InternalStatusInformation2TargetFilename + "...\n");
		InternalStatusInformation2Target.close();
	}


	// main entry point

	public void run(com.altova.io.Input IE5513Source, com.altova.io.Output InternalStatusInformation2Target) throws Exception {
		// Open the source(s)
		org.w3c.dom.Document doc_IE5513 = XmlTreeOperations.loadDocument(IE5513Source);
		varIE5513Instance = doc_IE5513;
		if (runDoesCloseAll)
			IE5513Source.close();

		// Create the target
		org.w3c.dom.Document InternalStatusInformation2Doc = (InternalStatusInformation2Target.getType() == com.altova.io.Output.IO_DOM) ? InternalStatusInformation2Target.getDocument() : XmlTreeOperations.createDocument();

		// Execute mapping

		main mapping = new main(new com.altova.xml.DOMDocumentAsMFNodeAdapter(varIE5513Instance, IE5513Source.getFilename()));

		com.altova.xml.MFDOMWriter.write(mapping, InternalStatusInformation2Doc);
		// Close the target
		XmlTreeOperations.saveDocument(InternalStatusInformation2Doc, InternalStatusInformation2Target, "UTF-8", false, false, true);

		
		if (runDoesCloseAll)
		{
			IE5513Source.close();
			InternalStatusInformation2Target.close();
		}
	}



}
