/**
 * ApiMessageAcknowledgementMapTolocalAppResult.java
 *
 * This file was generated by MapForce 2014r2sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */
package com.mapforce;
import com.altova.mapforce.*;
import com.altova.types.*;
import com.altova.xml.*;
import java.util.*;

public class ApiMessageAcknowledgementMapTolocalAppResult extends com.altova.TraceProvider 
{
	private boolean runDoesCloseAll = true;
	public void setCloseObjectsAfterRun(boolean c) {runDoesCloseAll = c;}
	public boolean getCloseObjectsAfterRun() {return runDoesCloseAll;}

	
	static class main implements IEnumerable
	{
		com.altova.mapforce.IMFNode var1_instance_ApiMessageAcknowledgement;
	
		public main(com.altova.mapforce.IMFNode var1_instance_ApiMessageAcknowledgement)
		{
			this.var1_instance_ApiMessageAcknowledgement = var1_instance_ApiMessageAcknowledgement;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}
		
		public static class Enumerator implements IEnumerator
		{
			int pos = 0;
			int state = 2;
			Object current;
			main closure;
			com.altova.mapforce.IEnumerable var2_filter_elements_qname;
			public Enumerator(main closure) 
			{
				this.closure = closure;
			}
			
			public Object current() {return current;}
			
			public int position() {return pos;}
			
			public boolean moveNext() throws Exception
			{
				while (state != 0)
				{
					switch (state) 
					{
					case 2:	if (moveNext_2()) return true; break;
 					}
				}
				return false;
			}

			private boolean moveNext_2() throws Exception {
				state = 0;				
				var2_filter_elements_qname = new com.altova.functions.Core.SequenceCache(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("ApiMessageAcknowledgement", "http://www.customsmatters.com/schemas/cab/declarationapi/ack"), closure.var1_instance_ApiMessageAcknowledgement));
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("localAppResult", ""), (new seq1_join(var2_filter_elements_qname)));
				pos++;
				return true;
			}

			
			public void close()
			{
				try
				{
				}
				catch (Exception e)
				{
				}
			}
		}
				
	}
	static class seq1_join implements IEnumerable
	{
		com.altova.mapforce.IEnumerable var1_filter_elements_qname;
	
		public seq1_join(com.altova.mapforce.IEnumerable var1_filter_elements_qname)
		{
			this.var1_filter_elements_qname = var1_filter_elements_qname;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}
		
		public static class Enumerator implements IEnumerator
		{
			int pos = 0;
			int state = 1;
			Object current;
			seq1_join closure;
			public Enumerator(seq1_join closure) 
			{
				this.closure = closure;
			}
			
			public Object current() {return current;}
			
			public int position() {return pos;}
			
			public boolean moveNext() throws Exception
			{
				while (state != 0)
				{
					switch (state) 
					{
					case 1:	if (moveNext_1()) return true; break;
					case 2:	if (moveNext_2()) return true; break;
 					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				current = com.altova.functions.Core.createAttribute(com.altova.functions.Core.createQName("xsi:noNamespaceSchemaLocation", "http://www.w3.org/2001/XMLSchema-instance"), com.altova.functions.Core.box("C:/Users/moredata/Desktop/KCXMapping/common/ApiMessageAckMapToLocalAppResult/localAppResult.xsd"));
				pos++;
				return true;
			}
			private boolean moveNext_2() throws Exception {
				state = 0;				
				if (!(com.altova.functions.Core.exists(closure.var1_filter_elements_qname))) {state = 0; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("GoodsDeclaration", ""), com.altova.functions.Core.box(com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("GoodsItem", ""), com.altova.functions.Core.box(com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("PositionError", ""), (new seq2_cond_cond_box(closure.var1_filter_elements_qname)))))));
				pos++;
				return true;
			}

			
			public void close()
			{
				try
				{
				}
				catch (Exception e)
				{
				}
			}
		}
				
	}
	static class seq2_cond_cond_box implements IEnumerable
	{
		com.altova.mapforce.IEnumerable var1_filter_elements_qname;
	
		public seq2_cond_cond_box(com.altova.mapforce.IEnumerable var1_filter_elements_qname)
		{
			this.var1_filter_elements_qname = var1_filter_elements_qname;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}
		
		public static class Enumerator implements IEnumerator
		{
			int pos = 0;
			int state = 1;
			Object current;
			seq2_cond_cond_box closure;
			public Enumerator(seq2_cond_cond_box closure) 
			{
				this.closure = closure;
			}
			
			public Object current() {return current;}
			
			public int position() {return pos;}
			
			public boolean moveNext() throws Exception
			{
				while (state != 0)
				{
					switch (state) 
					{
					case 1:	if (moveNext_1()) return true; break;
					case 3:	if (moveNext_3()) return true; break;
 					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 0;				
				if (!(com.altova.functions.Core.exists(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Status", "http://www.customsmatters.com/schemas/cab/declarationapi/ack"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname))))) {state = 0; return false; }
				if (!(com.altova.functions.Core.equal(com.altova.CoreTypes.nodeToString((com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Status", "http://www.customsmatters.com/schemas/cab/declarationapi/ack"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname)))), "SUCCESS"))) {state = 3; return false; }
				return false;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("ErrorText", ""), com.altova.functions.Core.box(com.altova.CoreTypes.nodeToString((com.altova.mapforce.IMFNode)com.altova.functions.Core.first(com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("Status", "http://www.customsmatters.com/schemas/cab/declarationapi/ack"), (com.altova.mapforce.IMFNode)com.altova.functions.Core.first(closure.var1_filter_elements_qname))))));
				pos++;
				return true;
			}

			
			public void close()
			{
				try
				{
				}
				catch (Exception e)
				{
				}
			}
		}
				
	}
	static class Outer implements IEnumerable
	{
		com.altova.mapforce.IMFNode var1_instance_ApiMessageAcknowledgement;
	
		public Outer(com.altova.mapforce.IMFNode var1_instance_ApiMessageAcknowledgement)
		{
			this.var1_instance_ApiMessageAcknowledgement = var1_instance_ApiMessageAcknowledgement;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}
		
		public static class Enumerator implements IEnumerator
		{
			int pos = 0;
			int state = 1;
			Object current;
			Outer closure;
			IEnumerator var2_box;
			public Enumerator(Outer closure) 
			{
				this.closure = closure;
			}
			
			public Object current() {return current;}
			
			public int position() {return pos;}
			
			public boolean moveNext() throws Exception
			{
				while (state != 0)
				{
					switch (state) 
					{
					case 1:	if (moveNext_1()) return true; break;
					case 2:	if (moveNext_2()) return true; break;
					case 3:	if (moveNext_3()) return true; break;
 					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var2_box = ((new main(closure.var1_instance_ApiMessageAcknowledgement))).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 2;				
				if (!var2_box.moveNext()) {state = 3; return false; }
				current = var2_box.current();
				pos++;
				return true;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				var2_box.close(); var2_box = null;
				return false;
			}

			
			public void close()
			{
				try
				{
				var2_box.close(); var2_box = null;
				}
				catch (Exception e)
				{
				}
			}
		}
				
	}



	// instances
	protected org.w3c.dom.Node varApiMessageAcknowledgement3Instance;

	public void run(String ApiMessageAcknowledgement3SourceFilename, String localAppResult2TargetFilename) throws Exception {
		// open source streams
		writeTrace("Loading " + ApiMessageAcknowledgement3SourceFilename + "...\n");
		com.altova.io.FileInput ApiMessageAcknowledgement3Source = new com.altova.io.FileInput(ApiMessageAcknowledgement3SourceFilename);
		// open target stream
		com.altova.io.FileOutput localAppResult2Target = new com.altova.io.FileOutput(localAppResult2TargetFilename);

		// run
		run(ApiMessageAcknowledgement3Source, localAppResult2Target);

		// close source streams
		ApiMessageAcknowledgement3Source.close();
		// close target stream
		writeTrace("Saving " + localAppResult2TargetFilename + "...\n");
		localAppResult2Target.close();
	}


	// main entry point

	public void run(com.altova.io.Input ApiMessageAcknowledgement3Source, com.altova.io.Output localAppResult2Target) throws Exception {
		// Open the source(s)
		org.w3c.dom.Document doc_ApiMessageAcknowledgement3 = XmlTreeOperations.loadDocument(ApiMessageAcknowledgement3Source);
		varApiMessageAcknowledgement3Instance = doc_ApiMessageAcknowledgement3;
		if (runDoesCloseAll)
			ApiMessageAcknowledgement3Source.close();

		// Create the target
		org.w3c.dom.Document localAppResult2Doc = (localAppResult2Target.getType() == com.altova.io.Output.IO_DOM) ? localAppResult2Target.getDocument() : XmlTreeOperations.createDocument();

		// Execute mapping

		main mapping = new main(new com.altova.xml.DOMDocumentAsMFNodeAdapter(varApiMessageAcknowledgement3Instance, ApiMessageAcknowledgement3Source.getFilename()));

		com.altova.xml.MFDOMWriter.write(mapping, localAppResult2Doc);
		// Close the target
		XmlTreeOperations.saveDocument(localAppResult2Doc, localAppResult2Target, "UTF-8", false, false, true);

		
		if (runDoesCloseAll)
		{
			ApiMessageAcknowledgement3Source.close();
			localAppResult2Target.close();
		}
	}



}
